development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://lntzxfpcteczpo:oDSBHMvDtDLfmg3-xMEwvPur2y@ec2-23-23-76-90.compute-1.amazonaws.com:5432/dcksrbshpt25bu
